# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bezerra Costa & Advogados Associados
email: contatos@bezerracosta.com.br
phone: +55 85 3036.0840
keywords: direito, fortaleza, advogados, direito empresarial, direito trabalhista, direito cível, direito ambiental
description: > # this means to ignore newlines until "baseurl:"
  Com a agilidade, versatilidade e a independência que o mercado exige, o escritório Bezerra Costa & Advogados Associados,
  disponibiliza as ferramentas jurídicas necessárias para que as empresas possam atuar com competitividade e segurança.
baseurl: "/bezerracosta" # the subpath of your site, e.g. /blog
url: "http://damisgarcia.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
excerpt_separator: ""

gems:
  - jekyll-assets
  - jekyll-angular
  - jekyll-coffeescript

assets:
  compress:
    css:
      development: false
      production: true
    js:
      development: false
      production: true
  debug: false
  cache: .asset-cache
  cdn: false
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  autowrite: false
  assets:
    - "*.png"
    - "*.jpg"
    - "bundle.css"
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - vendor
  features:
    liquid: false
    automatic_img_size: false
    automatic_img_alt : false
